### DISCUSSION TITLE
scale correction with marker integration doesnt work in ros2

### DISCUSSION THREAD

**Discussion by aimilios-cell-labs** [OpenVSLAM-Community/openvslam_ros#188] [Q&A] [answered]
Hello everyone, im using stella_vslam in ros2 jazzy and im trying to use an aruco marker for scale compensation. I have modified my yaml file to this:
 ```
#==============#
# Camera Model #
#==============#
Camera:
  name: "NR S3 Camera"
  setup: "monocular"
  model: "fisheye"

  fx: 257.23924003162307
  fy: 257.71963653721434
  cx: 314.86633456847943
  cy: 240.8685739906134

  k1: 0.40119951302962825
  k2: -0.0969676083701574
  k3: -0.08813202650058952
  k4: 0.051631310243367264

  fps: 30.0
  cols: 640
  rows: 480

  color_order: "BGR"

#================#
# ORB Parameters #
#================#
Feature:
  max_num_keypoints: 2000
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#
# Mapping:
#  baseline_dist_thr_ratio: 0.02
#  redundant_obs_ratio_thr: 0.9
#  num_covisibilities_for_landmark_generation: 20
#  num_covisibilities_for_landmark_fusion: 20
# #========================#
# # Initializer Parameters #
# #========================#
# Initializer:
#   scaling_factor: 1.0

MarkerModel:
 type: "aruco" 
 width: 0.145
 marker_size: 6
 max_markers: 1000
```    
but it doesnt seem to be working when i start the node with the camera directly pointing to the marker and the scaling seems to be inconsistent (every time i launch it different scaling). I have generated an aruco marker from the 6x6_1000 dictionary and after printing it the actual size is 145 cm. Is my configuration file correct for the marker integration in ros2? i tried to comment out the mapping and initializer parameters. Is there any logging available to check if the marker detection is working and used by the slam? I have tested aruco detection in general in my system in a ros node and it works fine by recognizing the aruco marker with id etc and calculates also the distance to it with good accuracy when im passing the camera parameters and size of the marker. Should i use a specific version of stella vslam library? 
![image](https://github.com/user-attachments/assets/49d94377-991b-4a73-b15c-c46d032c3da1)

Thank you very much in advance!
