### DISCUSSION TITLE
SLAM doesn't work properly and mapping jumps between points

### DISCUSSION THREAD

**Discussion by aliwaqas333** [OpenVSLAM-Community/openvslam_ros#38] [Q&A] [answered]
## [ERROR] [1627181523.437889922]: Transform failed: "odom" passed to lookupTransform argument source_frame does not exist. 
i am trying to run openvslam with Intel realsense D435 on my msi laptop.  I tried to comment the transform, i-e line 47 from `openvslam_ros.cc` , this made the error go away but still the SLAM doesn't work properly and mapping jumps between points.  
```C
    if (publish_tf_) {
```
Please help in this regards.

Please check this video to understand the problem.
# Video
[Video of the issue with screen recording](https://drive.google.com/file/d/1_zay7Juz3uqzDK_ICNYuTy39biBTcdwB/view)

# Launch File

```html
<launch>
    <!-- open realsense RGBD mode -->
    <include file="$(find realsense2_camera)/launch/rs_rgbd.launch" />

    <!-- open openVSLAM node  -->
    <node name="openvslam_node" pkg="openvslam_ros" type="run_slam" 
    args="-v $(find openvslam_ros)/orb_vocab/orb_vocab.fbow -c $(find openvslam_ros)/camera_config/rs_D435i_rgbd.yaml --map-db $(find openvslam_ros)/maps/map8.msg"
    output="screen"/>

    <!-- rename depth topics from realsense  -->
    <node name="image_transport_node" pkg="image_transport" type="republish" 
    args="raw in:=/camera/aligned_depth_to_color/image_raw raw out:=/camera/depth/image_raw"/>


</launch>
```
# Yaml File
My yaml config file is:

```yaml
Camera:
  name: "RS_D435 RGBD"
  setup: "RGBD"
  model: "perspective"

  fx: 608.6885681152344
  fy: 608.63482666015625
  cx: 311.8787841796875
  cy: 247.81253051757812

  k1: 0
  k2: 0
  p1: 0
  p2: 0
  k3: 0

  fps: 30.0
  cols: 640
  rows: 480

  # baseline is 50 mm
  focal_x_baseline: 36.3554139709

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

depth_threshold: 40.0
depthmap_factor: 1000.0
# ref: https://github.com/IntelRealSense/realsense-ros/issues/41

#================#
Feature:
  max_num_keypoints: 2000
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02

Initializer:
num_min_triangulated_pts: 400
#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.06
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.07
  camera_line_width: 2
  viewpoint_x: 0
  viewpoint_y: -20
  viewpoint_z: -0.1
  viewpoint_f: 2800
```
Thanks for taking time to read this. 
#37
